name: enducational_portal

on:
  push:
    branches:
      - portal
  pull_request:
    branches:
      - portal

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set version python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.1'

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run linter
        run: |
          flake8
